[package]
name = "k9-host-lib"
version = "0.1.0"
edition = "2021"

[features]
default = ["ble", "usb"]
ble = ["dep:btleplug"]
usb = ["dep:serialport"]

[dependencies]
k9-datachannel-proto = { package = "shared-datachannel-proto", path = "../shared-datachannel-proto", features = ["std"] }
tokio = { version = "1", features = ["sync", "time", "macros"] }
btleplug = { version = "0.11", optional = true }
serialport = { version = "4", optional = true }
thiserror = "1"
log = "0.4"
uuid = "1"
futures = "0.3"
